title: mxskb
description: MAXScript Knowledge Base

author:
  name: imaoki

copyright: 2016

url: https://imaoki.github.io
baseurl: "/mxskb"

excerpt_length: 40
paginate_path: "/page:num"
paginate: 10
permalink: /:year-:month-:day-:title
timezone: Asia/Tokyo
unpublished: false
use_minjs: true

debug:
  enabled: false
  template_path: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# highlighter: none

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
  footnote_backlink: "&crarr;"
  footnote_backlink_inline: true
  # syntax_highlighter: none
  syntax_highlighter_opts:
    disable: true
gfm_quirks: paragraph_end

plugins:
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-sitemap

exclude:
  - _site/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - src/
