title: kb
description: :-)

author:
  name: imaoki

copyright: 2016-2025

url: https://imaoki.github.io
baseurl: "/kb"

paginate_path: "/page:num"
paginate: 7
permalink: /:year-:month-:day-:title/
timezone: Asia/Tokyo
unpublished: false

# Original properties
use_minjs: true
excerpt_length: 30
debug:
  enabled: false
  template_path: true

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "assets/dist"
    values:
      sitemap: false

highlighter: none
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
  footnote_backlink: "&crarr;"
  footnote_backlink_inline: true
  syntax_highlighter: nil
  syntax_highlighter_opts:
    disable : true
gfm_quirks: paragraph_end

plugins:
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - src/
